services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${PGADMIN_PORT:-8081}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-felipe@okino.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  db:
    driver: local
  pgadmin:
    driver: local

    